#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/update-changelog.sh VERSION [NOTES_FILE]

Insert reviewed release notes into CHANGELOG.md under a new version section.
NOTES_FILE defaults to .release/notes-VERSION.md.

The script expects the CHANGELOG.md "## Unreleased" section to be empty, so
release notes come from the reviewed notes file generated by draft-changelog.sh.
USAGE
}

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  usage >&2
  exit 2
fi

case "$1" in
  -h|--help)
    usage
    exit 0
    ;;
esac

version="$1"
case "$version" in
  v*) ;;
  *) version="v$version" ;;
esac

notes_file="${2:-.release/notes-${version}.md}"
root=$(git rev-parse --show-toplevel)
cd "$root"

if [ ! -s "$notes_file" ]; then
  echo "error: notes file is missing or empty: $notes_file" >&2
  exit 1
fi

if [ ! -f CHANGELOG.md ]; then
  cat > CHANGELOG.md <<'EOF'
# Changelog

All notable changes to this project will be documented in this file.

## Unreleased
EOF
fi

if grep -Eq "^##[[:space:]]+${version}([[:space:]-]|$)" CHANGELOG.md; then
  echo "error: CHANGELOG.md already contains a section for $version" >&2
  exit 1
fi

if ! grep -Eq '^## Unreleased[[:space:]]*$' CHANGELOG.md; then
  echo "error: CHANGELOG.md must contain a '## Unreleased' section" >&2
  exit 1
fi

if ! awk '
  /^## Unreleased[[:space:]]*$/ { in_unreleased=1; next }
  /^## / && in_unreleased { exit found ? 1 : 0 }
  in_unreleased && NF { found=1 }
  END { if (in_unreleased) exit found ? 1 : 0 }
' CHANGELOG.md; then
  echo "error: CHANGELOG.md has non-empty Unreleased content; move or clear it before inserting generated notes" >&2
  exit 1
fi

date_utc=$(date -u +%F)
section_file=$(mktemp)
tmp_file=$(mktemp)
trap 'rm -f "$section_file" "$tmp_file"' EXIT

{
  printf '## %s - %s\n\n' "$version" "$date_utc"
  cat "$notes_file"
  printf '\n'
} > "$section_file"

awk -v section_file="$section_file" '
  /^## Unreleased[[:space:]]*$/ && !inserted {
    print
    print ""
    while ((getline line < section_file) > 0) {
      print line
    }
    close(section_file)
    inserted=1
    next
  }
  { print }
  END { if (!inserted) exit 2 }
' CHANGELOG.md > "$tmp_file"

mv "$tmp_file" CHANGELOG.md
trap - EXIT
rm -f "$section_file"

echo "Updated CHANGELOG.md with $version from $notes_file"
